export const R_SET_PAYLOADROLES= 'R_SET_PAYLOADROLES';
export const R_SHOW_MESSAGE_ROLES= 'R_SHOW_MESSAGE_ROLES';
export const R_SHOW_MESSAGE_ROLES_SUCCESS= 'R_SHOW_MESSAGE_ROLES_SUCCESS';
export const R_HIDE_MESSAGE_ROLES= 'R_HIDE_MESSAGE_ROLES';
export const R_GET_ROLESLIST= 'R_GET_ROLESLIST';
export const R_GET_ROLESLIST_SUCCESS= 'R_GET_ROLESLIST_SUCCESS';
export const R_POST_ROLES= 'R_POST_ROLES';
export const R_POST_ROLES_SUCCESS= 'R_POST_ROLES_SUCCESS';
export const R_GET_ROLES= 'R_GET_ROLES';
export const R_GET_ROLES_SUCCESS= 'R_GET_ROLES_SUCCESS';
export const R_PUT_ROLES= 'R_PUT_ROLES';
export const R_PUT_ROLES_SUCCESS= 'R_PUT_ROLES_SUCCESS';  
export const R_DELETE_ROLES= 'R_DELETE_ROLES';  
export const R_DELETE_ROLES_SUCCESS= 'R_DELETE_ROLES';  
export const R_SET_MESSAGE_ELIMINAR_ROLES= 'R_SET_MESSAGE_ELIMINAR_ROLES';  
export const EMPTY_DATA_INIT_ROLES='EMPTY_DATA_INIT_ROLES';

